name: Build and Push

on:
  push:
    branches:
      - dep  # Replace with the branch you want to trigger this action on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Replace with your dependencies setup

      - name: Build your project
        run: |
          # Replace this with commands to build your project

      - name: Login to Docker Hub (if pushing a Docker image)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Make sure to add Docker credentials as GitHub secrets

      - name: Push to repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-building and pushing changes"
          git push origin dep  # Change 'main' to your branch name if different
